window.AnnotationPluginManager.register({
    id: 'polygon', name: '多边形面片',
    getOcclusionReads: function(p, viewer, checkOccluded, isBackFace) {
        const midEl = viewer.querySelector(`[slot="${p.slot || p.dots[p.midIndex || Math.floor(p.dots.length/2)].slot}"]`); const dotReads = [];
        if (p.dots) { p.dots.forEach(d => { const el = viewer.querySelector(`[slot="${d.slot}"]`); if (el) dotReads.push({ r: el.getBoundingClientRect(), isOccluded: checkOccluded(el) || (isBackFace && isBackFace(d.norm)) }); }); }
        return { type: p.type, p, midEl, dotReads };
    },
    onPointerDown: function(slotName, posStr, normStr) {
        const slotPoly = `hotspot-poly-${pointIndex}-${currentPolygonDots.length}`; currentPolygonDots.push({slot: slotPoly, pos: posStr, norm: normStr});
        const dot = document.createElement('div'); dot.className = 'ink-anchor'; dot.setAttribute('slot', slotPoly); dot.setAttribute('data-position', posStr); dot.setAttribute('data-normal', normStr); dot.setAttribute('data-visibility-attribute', 'visible'); dot.setAttribute('visible', ''); viewer.appendChild(dot); updateSVG(); statusMsg.innerText = `面片顶点 ${currentPolygonDots.length} 已添加 (按 Enter 闭合)`;
    },
    finish: function() {
        if (currentPolygonDots.length >= 3) { let mx=0, my=0, mz=0, mnx=0, mny=0, mnz=0; currentPolygonDots.forEach(d => { const p = d.pos.replace(/m/g,'').split(' ').map(Number); const n = d.norm.replace(/m/g,'').split(' ').map(Number); mx+=p[0]; my+=p[1]; mz+=p[2]; mnx+=n[0]; mny+=n[1]; mnz+=n[2]; }); const len = currentPolygonDots.length; const nLen = Math.hypot(mnx, mny, mnz); const posStr = `${(mx/len).toFixed(4)}m ${(my/len).toFixed(4)}m ${(mz/len).toFixed(4)}m`; const normStr = `${(mnx/nLen||0).toFixed(4)}m ${(mny/nLen||0).toFixed(4)}m ${(mnz/nLen||0).toFixed(4)}m`; const midSlot = `hotspot-poly-mid-${pointIndex}`; pointsData.push({ id: pointIndex, type: 'polygon', slot: midSlot, pos: posStr, norm: normStr, text: `面片 ${pointIndex}`, dots: currentPolygonDots, color: defaultColor, hidden: false }); this.mountDOM(pointsData[pointsData.length-1], viewer); renderState(); updateSVG(); statusMsg.innerText = `面片 ${pointIndex} 创建完成`; pointIndex++; currentPolygonDots = []; } else if (currentPolygonDots.length > 0) { statusMsg.innerText = "顶点不足3个，无法闭合面片"; currentPolygonDots.forEach(d => { const el = viewer.querySelector(`[slot="${d.slot}"]`); if(el) el.remove(); }); currentPolygonDots = []; updateSVG(); }
    },
    renderSVG: function(item, htmlStr, ctx) {
        const p = item.p; const color = ctx.color; const isActive = item.midEl ? item.midEl.classList.contains('show-text') : false; const baseOpacity = isActive ? 1 : parseFloat(ctx.defaultOpacity); 
        const isOccluded = item.dotReads.some(dr => dr.isOccluded); const finalSvgAlpha = ctx.getRenderAlpha(isOccluded, baseOpacity);
        if(item.midEl) { const domAlpha = ctx.getRenderAlpha(isOccluded, 1); item.midEl.style.opacity = domAlpha; item.midEl.style.visibility = domAlpha <= 0 ? 'hidden' : 'visible'; }
        if(finalSvgAlpha > 0 && item.dotReads.length >= 3){ const ptsStr = item.dotReads.map(dr => `${dr.r.left + dr.r.width/2},${dr.r.top + dr.r.height/2}`).join(' '); htmlStr += `<polygon points="${ptsStr}" fill="transparent" stroke="transparent" stroke-width="20" style="pointer-events:auto;cursor:pointer;" onclick="document.querySelector('[slot=${p.slot}]').classList.toggle('show-text'); updateSVG(); if(window.scrollToListItem) window.scrollToListItem(${p.id});" />`; htmlStr += `<polygon points="${ptsStr}" fill="${ctx.hexToRgba(color, finalSvgAlpha * 0.3)}" stroke="${color}" stroke-width="2" stroke-linejoin="round" opacity="${finalSvgAlpha}" style="transition:opacity 0.2s;filter:drop-shadow(0 0 4px ${color});pointer-events:none;" />`; } return htmlStr;
    },
    renderPreviewSVG: function(htmlStr, ctx) {
        if (currentPolygonDots.length > 0) { const activeDotReads = []; currentPolygonDots.forEach(d => { const el = document.querySelector(`[slot="${d.slot}"]`); if(!el) return; activeDotReads.push({r: el.getBoundingClientRect(), isOccluded: (el.style.display==='none'||!el.hasAttribute('visible')||el.getAttribute('visible')==='false')}); }); const isOccluded = activeDotReads.some(dr => dr.isOccluded); const finalSvgAlpha = ctx.getRenderAlpha(isOccluded, 0.8); if (finalSvgAlpha > 0) { const ptsStr = activeDotReads.map(dr => `${dr.r.left + dr.r.width/2},${dr.r.top + dr.r.height/2}`).join(' '); htmlStr += `<polyline points="${ptsStr}" fill="${ctx.hexToRgba(defaultColor, 0.2 * (finalSvgAlpha/0.8))}" stroke="${defaultColor}" stroke-width="2" stroke-dasharray="4,4" opacity="${finalSvgAlpha}" style="pointer-events:none;" />`; } } return htmlStr;
    },
    renderConsumeSVG: function(item, htmlStr, ctx) {
        const p = item.p; const isHighlight = ctx.isHighlight; const color = ctx.color; const baseOpacity = isHighlight ? 1 : parseFloat(ctx.defaultOpacity); const isOccluded = item.dotReads.some(dr => dr.isOccluded); const finalSvgAlpha = ctx.getRenderAlpha(isOccluded, baseOpacity);
        if(item.midEl) { const domAlpha = ctx.getRenderAlpha(isOccluded, 1); item.midEl.style.opacity = domAlpha; item.midEl.style.visibility = domAlpha <= 0 ? 'hidden' : 'visible'; if(isHighlight) item.midEl.classList.add('active'); else item.midEl.classList.remove('active'); }
        if(finalSvgAlpha > 0 && item.dotReads.length >= 3){ const ptsStr = item.dotReads.map(dr => `${dr.r.left + dr.r.width/2},${dr.r.top + dr.r.height/2}`).join(' '); htmlStr += `<polygon class="svg-hit-path" data-id="${p.id}" points="${ptsStr}" fill="transparent" stroke="transparent" stroke-width="20" style="pointer-events:none;" />`; htmlStr += `<polygon points="${ptsStr}" fill="${ctx.hexToRgba(color, finalSvgAlpha * 0.3)}" stroke="${color}" stroke-width="2" stroke-linejoin="round" opacity="${finalSvgAlpha}" style="transition:opacity 0.2s;filter:drop-shadow(0 0 4px ${color});pointer-events:none;" />`; } return htmlStr;
    },
    mountDOM: function(p, viewer) { p.dots.forEach((dot, idx) => { const el = document.createElement('div'); el.className = 'ink-anchor'; el.setAttribute('slot', dot.slot); el.setAttribute('data-position', dot.pos); el.setAttribute('data-normal', dot.norm); el.setAttribute('data-visibility-attribute', 'visible'); el.setAttribute('visible', ''); viewer.appendChild(el); }); const midEl = document.createElement('div'); midEl.className = 'ink-anchor ink-mid'; midEl.setAttribute('slot', p.slot); midEl.setAttribute('data-position', p.pos); midEl.setAttribute('data-normal', p.norm); midEl.setAttribute('data-visibility-attribute', 'visible'); midEl.setAttribute('visible', ''); midEl.innerHTML = `<div class="HotspotAnnotation">${p.text}</div>`; midEl.setAttribute('data-id', p.id); const cid = p.id; midEl.addEventListener('click', function(evt) { if(window.tourState && window.tourState.isActive) return; this.classList.toggle('show-text'); if(typeof updateSVG !== 'undefined') updateSVG(); if(window.scrollToListItem) window.scrollToListItem(cid); }); viewer.appendChild(midEl); },
    unmountDOM: function(p, viewer) { if (p.dots) { p.dots.forEach(d => { const el = viewer.querySelector(`[slot="${d.slot}"]`); if(el) el.remove(); }); } const midEl = viewer.querySelector(`[slot="${p.slot}"]`); if(midEl) midEl.remove(); }
});