window.AnnotationPluginManager.register({
    id: 'line', name: '线段',
    getOcclusionReads: function(p, viewer, checkOccluded, isBackFace) {
        const midEl = viewer.querySelector(`[slot="${p.slot || p.dots[p.midIndex || Math.floor(p.dots.length/2)].slot}"]`); const dotReads = [];
        if (p.dots) { p.dots.forEach(d => { const el = viewer.querySelector(`[slot="${d.slot}"]`); if (el) dotReads.push({ r: el.getBoundingClientRect(), isOccluded: checkOccluded(el) || (isBackFace && isBackFace(d.norm)) }); }); }
        return { type: p.type, p, midEl, dotReads };
    },
    onPointerMove: function(e) {
        let isStart = false; if (!isDrawing) { isDrawing = true; lastDrawX = e.clientX; lastDrawY = e.clientY; currentLineDots = []; isStart = true; }
        const dist = Math.hypot(e.clientX - lastDrawX, e.clientY - lastDrawY); if (isStart || dist > 15) { const hit = viewer.positionAndNormalFromPoint(e.clientX, e.clientY); if (hit) {
        const pos = `${hit.position.x.toFixed(4)}m ${hit.position.y.toFixed(4)}m ${hit.position.z.toFixed(4)}m`; const norm = `${hit.normal.x.toFixed(4)}m ${hit.normal.y.toFixed(4)}m ${hit.normal.z.toFixed(4)}m`; const slotName = `hotspot-ink-${pointIndex}-${currentLineDots.length}`; currentLineDots.push({ slot: slotName, pos: pos, norm: norm });
        const dot = document.createElement('div'); dot.className = 'ink-anchor'; dot.setAttribute('slot', slotName); dot.setAttribute('data-position', pos); dot.setAttribute('data-normal', norm); dot.setAttribute('data-visibility-attribute', 'visible'); dot.setAttribute('visible', '');
        viewer.appendChild(dot); lastDrawX = e.clientX; lastDrawY = e.clientY; requestAnimationFrame(() => updateSVGActiveLine()); } }
    },
    onPointerDown: function() {}, finish: function() {
        if (isDrawing) { isDrawing = false; if (currentLineDots.length > 0) { currentLineDots.forEach(d => { const temp = viewer.querySelector(`[slot="${d.slot}"]`); if(temp) temp.remove(); }); const midIndex = Math.floor(currentLineDots.length / 2); const midDot = currentLineDots[midIndex]; pointsData.push({ id: pointIndex, type: 'line', slot: midDot.slot, pos: midDot.pos, norm: midDot.norm, text: `线段 ${pointIndex}`, dots: currentLineDots, midIndex: midIndex, color: defaultColor, hidden: false }); this.mountDOM(pointsData[pointsData.length-1], viewer); renderState(); updateSVG(); statusMsg.innerText = `线段 ${pointIndex} 绘制完成`; pointIndex++; } }
    },
    renderSVG: function(item, htmlStr, ctx) {
        const p = item.p; const color = ctx.color; const isActive = item.midEl ? item.midEl.classList.contains('show-text') : false; const baseOpacity = isActive ? 1 : parseFloat(ctx.defaultOpacity); 
        const someOccluded = item.dotReads.some(dr => dr.isOccluded); const ghostAlpha = ctx.getRenderAlpha(true, 1); 
        if(item.midEl) { const midOccluded = item.dotReads[p.midIndex||Math.floor(p.dots.length/2)]?.isOccluded; const domAlpha = ctx.getRenderAlpha(midOccluded, 1); item.midEl.style.opacity = domAlpha; item.midEl.style.visibility = domAlpha <= 0 ? 'hidden':'visible'; }
        let dStrAll = ''; let dStrVisible = ''; let isFirstAll = true, isFirstVis = true; let len3D = 0;
        item.dotReads.forEach((dr, i) => { dStrAll += `${isFirstAll ? 'M' : 'L'}${dr.r.left + dr.r.width/2} ${dr.r.top + dr.r.height/2} `; isFirstAll = false; if (dr.isOccluded) { isFirstVis = true; } else { dStrVisible += `${isFirstVis ? 'M' : 'L'}${dr.r.left + dr.r.width/2} ${dr.r.top + dr.r.height/2} `; if (!isFirstVis && i > 0 && !item.dotReads[i-1].isOccluded) { const p1 = p.dots[i-1].pos.replace(/m/g,'').split(' ').map(Number); const p2 = p.dots[i].pos.replace(/m/g,'').split(' ').map(Number); len3D += Math.hypot(p1[0]-p2[0], p1[1]-p2[1], p1[2]-p2[2]); } isFirstVis = false; } });
        const midSlot = p.dots[p.midIndex||Math.floor(p.dots.length/2)].slot; htmlStr += `<path d="${dStrAll}" fill="none" stroke="transparent" stroke-width="40" style="pointer-events: auto; cursor: pointer;" onclick="document.querySelector('[slot=&quot;${midSlot}&quot;]').classList.toggle('show-text'); updateSVG(); if(window.scrollToListItem) window.scrollToListItem(${p.id});" />`;
        if (someOccluded && ghostAlpha > 0) htmlStr += `<path d="${dStrAll}" fill="none" stroke="${color}" stroke-width="1.5" stroke-dasharray="4,4" opacity="${ghostAlpha}" style="pointer-events: none;" />`;
        if (dStrVisible) { const totalDashes = Math.max(4, len3D * 120); const patternLength = 100/totalDashes; const dashLen = patternLength * 0.4; const gapLen = patternLength * 0.6; htmlStr += `<path d="${dStrVisible}" pathLength="100" fill="none" stroke="${color}" stroke-width="3" stroke-dasharray="${dashLen},${gapLen}" opacity="${baseOpacity}" style="transition: opacity 0.2s; filter: drop-shadow(0 0 4px ${color}); pointer-events: none;" />`; } return htmlStr;
    },
    renderConsumeSVG: function(item, htmlStr, ctx) {
        const p = item.p; const isHighlight = ctx.isHighlight; const color = ctx.color; const baseOpacity = isHighlight ? 1 : parseFloat(ctx.defaultOpacity); const someOccluded = item.dotReads.some(dr => dr.isOccluded); const ghostAlpha = ctx.getRenderAlpha(true, 1);
        if(item.midEl) { const midOccluded = item.dotReads[p.midIndex||Math.floor(p.dots.length/2)]?.isOccluded; const domAlpha = ctx.getRenderAlpha(midOccluded, 1); item.midEl.style.opacity = domAlpha; item.midEl.style.visibility = domAlpha <= 0 ? 'hidden':'visible'; if(isHighlight) item.midEl.classList.add('active'); else item.midEl.classList.remove('active'); }
        let dStrAll = ''; let dStrVisible = ''; let isFirstAll = true, isFirstVis = true; let len3D = 0; 
        item.dotReads.forEach((dr, i) => { dStrAll += `${isFirstAll ? 'M' : 'L'}${dr.r.left + dr.r.width/2} ${dr.r.top + dr.r.height/2} `; isFirstAll = false; if (dr.isOccluded) { isFirstVis = true; } else { dStrVisible += `${isFirstVis ? 'M' : 'L'}${dr.r.left + dr.r.width/2} ${dr.r.top + dr.r.height/2} `; if (!isFirstVis && i > 0 && !item.dotReads[i-1].isOccluded) { const p1 = p.dots[i-1].pos.replace(/m/g,'').split(' ').map(Number); const p2 = p.dots[i].pos.replace(/m/g,'').split(' ').map(Number); len3D += Math.hypot(p1[0]-p2[0], p1[1]-p2[1], p1[2]-p2[2]); } isFirstVis = false; } });
        htmlStr += `<path class="svg-hit-path" data-id="${p.id}" d="${dStrAll}" fill="none" stroke="transparent" stroke-width="40" style="pointer-events: none;" />`;
        if (someOccluded && ghostAlpha > 0) htmlStr += `<path d="${dStrAll}" fill="none" stroke="${color}" stroke-width="1.5" stroke-dasharray="4,4" opacity="${ghostAlpha}" style="pointer-events: none;" />`;
        if (dStrVisible) { const totalDashes = Math.max(4, len3D * 120); const patternLength = 100 / totalDashes; const dashLen = patternLength * 0.4; const gapLen = patternLength * 0.6;  htmlStr += `<path d="${dStrVisible}" pathLength="100" fill="none" stroke="${color}" stroke-width="3" stroke-dasharray="${dashLen},${gapLen}" opacity="${baseOpacity}" style="transition: opacity 0.2s; filter: drop-shadow(0 0 4px ${color}); pointer-events: none;" />`; } return htmlStr;
    },
    mountDOM: function(p, viewer) { p.dots.forEach((dot, idx) => { const el = document.createElement('div'); el.className = 'ink-anchor'; if (idx === (p.midIndex || Math.floor(p.dots.length/2))) { el.classList.add('ink-mid'); el.innerHTML = `<div class="HotspotAnnotation">${p.text}</div>`; el.setAttribute('data-id', p.id); el.addEventListener('click', function(evt) { if(window.tourState && window.tourState.isActive) return; this.classList.toggle('show-text'); if(typeof updateSVG !== 'undefined') updateSVG(); if(window.scrollToListItem) window.scrollToListItem(p.id); }); } el.setAttribute('slot', dot.slot); el.setAttribute('data-position', dot.pos); el.setAttribute('data-normal', dot.norm); el.setAttribute('data-visibility-attribute', 'visible'); el.setAttribute('visible', ''); viewer.appendChild(el); }); },
    unmountDOM: function(p, viewer) { if (p.dots) { p.dots.forEach(d => { const el = viewer.querySelector(`[slot="${d.slot}"]`); if(el) el.remove(); }); } }
});