window.AnnotationPluginManager.register({
    id: 'normal-arrow', name: '法线箭头',
    getOcclusionReads: function(p, viewer, checkOccluded, isBackFace) {
        const el = viewer.querySelector(`[slot="${p.slot}"]`); const elEnd = viewer.querySelector(`[slot="${p.slotEnd}"]`); const elP1 = viewer.querySelector(`[slot="${p.slotP1}"]`); const elP2 = viewer.querySelector(`[slot="${p.slotP2}"]`); const elP3 = viewer.querySelector(`[slot="${p.slotP3}"]`);
        if (el && elEnd) return { type: p.type, p, el, elEnd, elP1, elP2, elP3, isOccluded: checkOccluded(el) || (isBackFace && isBackFace(p.norm)) }; return null;
    },
    onPointerDown: function(slotName, posStr, normStr, hitExact, e, viewer) {
        let finalNx = hitExact.normal.x, finalNy = hitExact.normal.y, finalNz = hitExact.normal.z;
        // 极致解耦：箭头插件自己去探测鼠标周围 9 个点的法线做平滑，不再依赖主页面
        if (e && e.shiftKey) {
            let nx = 0, ny = 0, nz = 0, count = 0; const radius = 8;
            const offsets = [[0,0],[-radius,0],[radius,0],[0,-radius],[0,radius],[-radius,-radius],[radius,radius],[-radius,radius],[radius,-radius]]; 
            for (let [dx, dy] of offsets) {
                const h = viewer.positionAndNormalFromPoint(e.clientX + dx, e.clientY + dy); 
                if (h != null) { nx += h.normal.x; ny += h.normal.y; nz += h.normal.z; count++; } 
            }
            if (count > 0) { const len = Math.hypot(nx, ny, nz); if (len > 0) { finalNx = nx/len; finalNy = ny/len; finalNz = nz/len; } }
        }
        const smoothNormStr = `${finalNx.toFixed(4)}m ${finalNy.toFixed(4)}m ${finalNz.toFixed(4)}m`;

        const aLen = parseFloat(document.getElementById('arrow-length').value) || 0.05; const px2 = hitExact.position.x + finalNx * aLen; const py2 = hitExact.position.y + finalNy * aLen; const pz2 = hitExact.position.z + finalNz * aLen;
        const hl = aLen * 0.28, hw = aLen * 0.08; const pbx = px2 - finalNx * hl, pby = py2 - finalNy * hl, pbz = pz2 - finalNz * hl; let up = Math.abs(finalNy) > 0.5 ? [1, 0, 0] : [0, 1, 0]; let ux = finalNy * up[2] - finalNz * up[1], uy = finalNz * up[0] - finalNx * up[2], uz = finalNx * up[1] - finalNy * up[0]; let uLen = Math.hypot(ux, uy, uz); if (uLen < 0.0001) { ux=1; uy=0; uz=0; uLen=1; } ux /= uLen; uy /= uLen; uz /= uLen; let vx = uy * finalNz - uz * finalNy, vy = uz * finalNx - ux * finalNz, vz = ux * finalNy - uy * finalNx;
        const w1x = pbx + hw * ux, w1y = pby + hw * uy, w1z = pbz + hw * uz; const w2x = pbx + hw * (-0.5*ux + 0.866*vx), w2y = pby + hw * (-0.5*uy + 0.866*vy), w2z = pbz + hw * (-0.5*uz + 0.866*vz); const w3x = pbx + hw * (-0.5*ux - 0.866*vx), w3y = pby + hw * (-0.5*uy - 0.866*vy), w3z = pbz + hw * (-0.5*uz - 0.866*vz);
        const posBStr = `${px2.toFixed(4)}m ${py2.toFixed(4)}m ${pz2.toFixed(4)}m`; const slotNameEnd = `hotspot-end-${pointIndex}`, slotP1 = `hotspot-p1-${pointIndex}`, slotP2 = `hotspot-p2-${pointIndex}`, slotP3 = `hotspot-p3-${pointIndex}`;
        pointsData.push({ id: pointIndex, type: 'normal-arrow', slot: slotName, slotEnd: slotNameEnd, slotP1: slotP1, slotP2: slotP2, slotP3: slotP3, pos: posStr, posB: posBStr, posP1: `${w1x.toFixed(4)}m ${w1y.toFixed(4)}m ${w1z.toFixed(4)}m`, posP2: `${w2x.toFixed(4)}m ${w2y.toFixed(4)}m ${w2z.toFixed(4)}m`, posP3: `${w3x.toFixed(4)}m ${w3y.toFixed(4)}m ${w3z.toFixed(4)}m`, norm: smoothNormStr, text: `法线 ${pointIndex}`, color: defaultColor, hidden: false });
        this.mountDOM(pointsData[pointsData.length-1], viewer);
    },
    renderSVG: function(item, htmlStr, ctx) {
        const p = item.p; const color = ctx.color; const el = item.el; const isActive = el.classList.contains('show-text'); const baseOpacity = isActive ? 1 : parseFloat(ctx.defaultOpacity);
        const domAlpha = ctx.getRenderAlpha(item.isOccluded, 1); el.style.opacity = domAlpha; el.style.visibility = domAlpha <= 0 ? 'hidden' : 'visible'; el.style.backgroundColor = ctx.hexToRgba(color, baseOpacity); el.style.boxShadow = isActive ? `0 0 10px ${ctx.hexToRgba(color, baseOpacity)}` : 'none';
        const finalSvgAlpha = ctx.getRenderAlpha(item.isOccluded, baseOpacity);
        if (finalSvgAlpha > 0) {
            const rTip = item.elEnd.getBoundingClientRect(); const rTail = el.getBoundingClientRect(); if(!rTip.width || (rTip.left === 0 && rTip.top === 0)) return htmlStr;
            const Tip = {x: rTip.left + rTip.width/2, y: rTip.top + rTip.height/2}; const Tail = {x: rTail.left + rTail.width/2, y: rTail.top + rTail.height/2}; const toggleCode = `document.querySelector('[slot=${p.slot}]').classList.toggle('show-text');updateSVG();if(window.scrollToListItem)window.scrollToListItem(${p.id});`; htmlStr += `<line x1="${Tail.x}" y1="${Tail.y}" x2="${Tip.x}" y2="${Tip.y}" stroke="transparent" stroke-width="40" style="pointer-events:auto;cursor:pointer;" onclick="${toggleCode}" />`;
            if(item.elP1 && item.elP2 && item.elP3){ const rP1 = item.elP1.getBoundingClientRect(), rP2 = item.elP2.getBoundingClientRect(), rP3 = item.elP3.getBoundingClientRect(); if(rP1.left === 0 && rP1.top === 0) return htmlStr; const P1 = {x: rP1.left+rP1.width/2, y: rP1.top+rP1.height/2}; const P2 = {x: rP2.left+rP2.width/2, y: rP2.top+rP2.height/2}; const P3 = {x: rP3.left+rP3.width/2, y: rP3.top+rP3.height/2}; const xc = (P1.x+P2.x+P3.x)/3, yc = (P1.y+P2.y+P3.y)/3; htmlStr += `<line x1="${Tail.x}" y1="${Tail.y}" x2="${xc}" y2="${yc}" stroke="${color}" stroke-width="3" opacity="${finalSvgAlpha}" style="transition:opacity 0.2s;filter:drop-shadow(0 0 4px ${color});pointer-events:none;" />`; const drawFacet = (pA, pB, pC, overlayCol, overlayOp) => { const cross = (pB.x - pA.x) * (pC.y - pA.y) - (pB.y - pA.y) * (pC.x - pA.x); if (cross > 0) { htmlStr += `<polygon points="${pA.x},${pA.y} ${pB.x},${pB.y} ${pC.x},${pC.y}" fill="${color}" opacity="${finalSvgAlpha}" stroke="${color}" stroke-width="1.5" stroke-linejoin="round" style="pointer-events:none;" />`; if (overlayOp > 0) htmlStr += `<polygon points="${pA.x},${pA.y} ${pB.x},${pB.y} ${pC.x},${pC.y}" fill="${overlayCol}" opacity="${overlayOp * finalSvgAlpha}" style="pointer-events:none;" />`; } }; drawFacet(Tip, P1, P2, '#ffffff', 0.3); drawFacet(Tip, P2, P3, '#000000', 0.2); drawFacet(Tip, P3, P1, '#000000', 0.5); drawFacet(P1, P3, P2, '#000000', 0.7); } 
        } return htmlStr;
    },
    renderConsumeSVG: function(item, htmlStr, ctx) {
        const p = item.p; const isHighlight = ctx.isHighlight; const color = ctx.color; const el = item.el; const baseOpacity = isHighlight ? 1 : parseFloat(ctx.defaultOpacity);
        const domAlpha = ctx.getRenderAlpha(item.isOccluded, 1); el.style.opacity = domAlpha; el.style.visibility = domAlpha <= 0 ? 'hidden' : 'visible';
        if(isHighlight) el.classList.add('active'); else el.classList.remove('active'); el.style.backgroundColor = ctx.hexToRgba(color, baseOpacity); el.style.boxShadow = isHighlight ? `0 0 10px ${ctx.hexToRgba(color, baseOpacity)}` : 'none'; el.style.transform = isHighlight ? 'scale(1.2)' : 'none';
        const finalSvgAlpha = ctx.getRenderAlpha(item.isOccluded, baseOpacity);
        if (finalSvgAlpha > 0) { const rTip = item.elEnd.getBoundingClientRect(); const rTail = el.getBoundingClientRect(); if(!rTip.width || (rTip.left === 0 && rTip.top === 0)) return htmlStr; const Tip = {x: rTip.left + rTip.width/2, y: rTip.top + rTip.height/2}; const Tail = {x: rTail.left + rTail.width/2, y: rTail.top + rTail.height/2}; htmlStr += `<line class="svg-hit-path" data-id="${p.id}" x1="${Tail.x}" y1="${Tail.y}" x2="${Tip.x}" y2="${Tip.y}" stroke="transparent" stroke-width="40" style="pointer-events:none;" />`; if(item.elP1 && item.elP2 && item.elP3){ const rP1 = item.elP1.getBoundingClientRect(), rP2 = item.elP2.getBoundingClientRect(), rP3 = item.elP3.getBoundingClientRect(); if(rP1.left === 0 && rP1.top === 0) return htmlStr; const P1 = {x: rP1.left+rP1.width/2, y: rP1.top+rP1.height/2}; const P2 = {x: rP2.left+rP2.width/2, y: rP2.top+rP2.height/2}; const P3 = {x: rP3.left+rP3.width/2, y: rP3.top+rP3.height/2}; const xc = (P1.x+P2.x+P3.x)/3, yc = (P1.y+P2.y+P3.y)/3; htmlStr += `<line x1="${Tail.x}" y1="${Tail.y}" x2="${xc}" y2="${yc}" stroke="${color}" stroke-width="3" opacity="${finalSvgAlpha}" style="transition:opacity 0.2s;filter:drop-shadow(0 0 4px ${color});pointer-events:none;" />`; const drawFacet = (pA, pB, pC, overlayCol, overlayOp) => { const cross = (pB.x - pA.x) * (pC.y - pA.y) - (pB.y - pA.y) * (pC.x - pA.x); if (cross > 0) { htmlStr += `<polygon points="${pA.x},${pA.y} ${pB.x},${pB.y} ${pC.x},${pC.y}" fill="${color}" opacity="${finalSvgAlpha}" stroke="${color}" stroke-width="1.5" stroke-linejoin="round" style="pointer-events:none;" />`; if (overlayOp > 0) htmlStr += `<polygon points="${pA.x},${pA.y} ${pB.x},${pB.y} ${pC.x},${pC.y}" fill="${overlayCol}" opacity="${overlayOp * finalSvgAlpha}" style="pointer-events:none;" />`; } }; drawFacet(Tip, P1, P2, '#ffffff', 0.3); drawFacet(Tip, P2, P3, '#000000', 0.2); drawFacet(Tip, P3, P1, '#000000', 0.5); drawFacet(P1, P3, P2, '#000000', 0.7); } } return htmlStr;
    },
    mountDOM: function(p, viewer) { const el = document.createElement('button'); el.className = 'preview-hotspot'; el.setAttribute('slot', p.slot); el.setAttribute('data-position', p.pos); el.setAttribute('data-normal', p.norm); el.setAttribute('data-visibility-attribute', 'visible'); el.setAttribute('visible', ''); el.setAttribute('data-id', p.id); el.innerHTML = `<div class="HotspotAnnotation">${p.text}</div>`; const cid = p.id; el.addEventListener('click', function(evt) { if(window.tourState) return; this.classList.toggle('show-text'); if(typeof updateSVG !== 'undefined') updateSVG(); if(window.scrollToListItem) window.scrollToListItem(cid); }); viewer.appendChild(el); const createAnch = (_slot, _pos) => { if(!_slot || !_pos) return; const elA = document.createElement('div'); elA.className = 'ink-anchor'; elA.setAttribute('slot', _slot); elA.setAttribute('data-position', _pos); elA.setAttribute('data-visibility-attribute', 'visible'); elA.setAttribute('visible', ''); viewer.appendChild(elA); }; createAnch(p.slotEnd, p.posB || p.pos); createAnch(p.slotP1, p.posP1 || p.pos); createAnch(p.slotP2, p.posP2 || p.pos); createAnch(p.slotP3, p.posP3 || p.pos); },
    unmountDOM: function(p, viewer) { [p.slot, p.slotEnd, p.slotP1, p.slotP2, p.slotP3].forEach(s => { if(s){ const el = viewer.querySelector(`[slot="${s}"]`); if(el) el.remove(); } }); }
});